// File: src/app/(inicio)/layout.js

import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import Link from 'next/link';
import BotaoSair from "./../../components/personalizados/botaoSair";
import NavBarLinks from "./../../components/personalizados/navBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  subsets: ["latin"],
  display: 'swap',
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.className} ${geistMono.className}`}>
      <body className="antialiased">
        <nav className="flex justify-between p-4 bg-stone-800 text-gray-100">
          <div>
            <h1 className='text-xl font-bold'>R4M<span className='ml-1 text-orange-400'>Polidores</span></h1>
          </div>
          <NavBarLinks></NavBarLinks>
          <div>
            <BotaoSair />
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}