import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import Link from 'next/link';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  subsets: ["latin"],
  display: 'swap', // Adicione isso
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.className} ${geistMono.className}`}>
      <body className="antialiased">
        <nav className="flex justify-between p-4 bg-stone-800 text-gray-100">
          <div>
            <h1 className='text-xl font-bold'>R4M<span className='ml-1 text-orange-400'>Polidores</span></h1>
          </div>
          <div>
            <Link
              href="/produtos"
              className="mr-6 transition-colors hover:text-orange-400"
            >
              Produtos
            </Link>
            <a
              href="/organizacao"
              className="mr-6 transition-colors hover:text-orange-400"
            >
              Organização
            </a>
            <a
              href="/admin"
              className="transition-colors hover:text-orange-400"
            >
              Administração
            </a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}